### ISSUE TITLE
"py -2 -m pip install pyamg --upgrade" to  4.0.0 fails in MS Win, while "py -3..." upgraded fine

### ISSUE THREAD

**Issue by lobpcg** [pyamg/pyamg#233]
"py -3 -m pip install pyamg --upgrade"
worked fine on MS Win to upgrade to 4.0.0, while
"py -2 -m pip install pyamg --upgrade"
fails: 
...
 Running setup.py install for pyamg ... error
    Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\name\\appdata\\local\\temp\\pip-install-ef0umf\\pyamg\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\name\appdata\local\temp\pip-record-bcj40l\install-record.txt --single-version-externally-managed --compile:
    12cf36e46f091253710f5fc5d3868b3ca78d515c
    4.0.0
...
    C:\Users\Name\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\Include -IC:\Users\Name\AppData\Roaming\Python\Python27\Include -IC:\Python27\include -IC:\Python27\PC -IC:\Python27\lib\site-packages\numpy\core\include /Tppyamg/amg_core/evolution_strength_bind.cpp /Fobuild\temp.win-amd64-2.7\Release\pyamg/amg_core/evolution_strength_bind.obj /EHsc /DVERSION_INFO=\"4.0.0\"
    evolution_strength_bind.cpp
    c:\python27\include\pybind11\detail/common.h(71) : fatal error C1189: #error :  pybind11 requires MSVC 2015 update 3 or newer
    error: command 'C:\\Users\\Name\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
  Rolling back uninstall of pyamg
Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\name\\appdata\\local\\temp\\pip-install-ef0umf\\pyamg\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\name\appdata\local\temp\pip-record-bcj40l\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\name\appdata\local\temp\pip-install-ef0umf\pyamg\

**Comment by lukeolson** [comment]
We only build wheels for Python 3 (https://pypi.org/project/pyamg/#files).  IIRC this is due to the lack of C++ and VS2017 support for Python 2 in appveyor, and the VS2017 (or 2015 u3) is needed for pybind11, which seems to be the issue here.  Have you tried to upgrade MSVC?

**Comment by lobpcg** [comment]
I have the latest VS2017 and 2015 u3. May be the issue is that my Python 2 install is stand alone, not downloaded and installed as a part of VS?

**Comment by lukeolson** [comment]
@lobpcg this one is old and I'm rolling out an update.  but keep me posted your windows install is still having issues ...
